# Generated by Django 3.2 on 2021-04-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20210429_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='text',
            new_name='title',
        ),
    ]
